#!/usr/bin/env python3
"""Passive BLE scan to see (and configure) the battery packs the Pi can actually hear.

    python deploy/ble_scan.py                 # list every BLE device heard (MAC, RSSI, name)
    python deploy/ble_scan.py AA:.. BB:..     # check specific MACs: FOUND / MISSING
    python deploy/ble_scan.py --emit          # print ready-to-paste packs.conf lines

Scanning is passive (no connection), so it works even with the service up — but it's cleaner to
`systemctl --user stop solardash` first so nothing is mid-connect (a pack the Pi is connected to
won't advertise). Needs bleak (already installed for the BMS poller).

`--emit` is the anti-typo path: it prints packs.conf lines straight from what the radio hears, so
a MAC is never transcribed by hand (which is how an 08-vs-0B slips in).
"""
import asyncio
import sys

from bleak import BleakScanner

SECS = 15.0
# Packs advertise names like "ECO-LFP48100-3U-0B406A" (ECO) or "xiaoxiang BMS" (generic JBD).
PACK_HINTS = ("LFP", "BMS")


def _rssi(dev, adv):
    r = getattr(adv, "rssi", None)
    return r if r is not None else getattr(dev, "rssi", None)


def _is_pack(name: str) -> bool:
    up = (name or "").upper()
    return any(h in up for h in PACK_HINTS)


async def _scan():
    seen = {}  # MAC -> (name, rssi), keeping the strongest RSSI seen

    def cb(dev, adv):
        name = adv.local_name or dev.name or "?"
        rssi = _rssi(dev, adv)
        old = seen.get(dev.address.upper())
        if old is None or (rssi is not None and (old[1] is None or rssi > old[1])):
            seen[dev.address.upper()] = (name, rssi)

    scanner = BleakScanner(detection_callback=cb)
    await scanner.start()
    await asyncio.sleep(SECS)
    await scanner.stop()
    return seen


def main():
    args = sys.argv[1:]
    emit = "--emit" in args
    targets = [a.upper() for a in args if not a.startswith("--")]

    print(f"scanning {SECS:.0f}s ...", file=sys.stderr)
    seen = asyncio.run(_scan())

    if emit:
        packs = sorted(((m, n, r) for m, (n, r) in seen.items() if _is_pack(n)), key=lambda x: x[1])
        if not packs:
            print("# no BMS packs heard — is the service stopped and are the packs powered?")
            return
        print("# packs.conf — generated by ble_scan.py --emit. Verify each MAC against the")
        print("# advertised name in the comment, adjust positions/names, then save as packs.conf.")
        print("#")
        print("# MAC                  pos  name")
        for i, (mac, name, rssi) in enumerate(packs, start=1):
            rssi_s = f"{rssi} dBm" if rssi is not None else "?"
            print(f"{mac}   {i:>2}   # {name}   {rssi_s}")
        return

    if targets:
        print("target check:")
        for mac in targets:
            if mac in seen:
                name, rssi = seen[mac]
                print(f"  FOUND    {mac}  {rssi} dBm  {name}")
            else:
                print(f"  MISSING  {mac}  not heard")
    print(f"all devices heard ({len(seen)}, strongest first):")
    for mac, (name, rssi) in sorted(seen.items(), key=lambda kv: -(kv[1][1] or -999)):
        tag = "  <- pack" if _is_pack(name) else ""
        mark = "  <- target" if mac in targets else ""
        print(f"  {mac}  {rssi} dBm  {name}{tag}{mark}")


if __name__ == "__main__":
    main()
